### ISSUE TITLE
Collaborator status? (or create COVERALLS_TOKEN secret)

### ISSUE THREAD

**Issue by mohawk2** [mohawk2/Graph#16]
@neilb similar request to https://github.com/eserte/graphviz-makefile/issues/4:

I'm hoping to make the GitHub Actions work completely including Coveralls operation. Could you either create the relevant secret on the repo and say here, so I can update the config, or make me a collaborator (I think) so I can do it myself? As a stretch goal, could you transfer this repo to the https://github.com/graphviz-perl organisation?

**Comment by mohawk2** [comment]
Thanks to https://github.com/kan/coveralls-perl/pull/33 there is now working coverage-reporting, so no need for making the Coveralls secret :-)

**Comment by neilb** [comment]
I tried to transfer to graphviz-perl, but it wouldn't let me because I'm not a member of the organisation, so instead I've triggered a transfer to you -- you should get an email asking you to confirm that you accept the transfer.

**Comment by mohawk2** [comment]
Received, thanks! Let me know if you're interested in being part of graphviz-perl.

**Comment by neilb** [comment]
> Let me know if you're interested in being part of graphviz-perl

My heart says "yes", but my brain says "you're never going to get any time for it", so best not, thanks :-)

**Comment by mohawk2** [comment]
Fair! Let me know if you have any feature ideas. I'm thinking about adding what modern graph databases call "categories" (or labels) to both nodes and edges. I even have a design ready (they will use another AdjacencyMap).
